# Generated by Django 2.0.6 on 2018-10-31 10:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='user_profilepics')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 31, 16, 24, 49, 88024))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 31, 16, 24, 49, 87023)),
        ),
    ]
