# Generated by Django 2.0.6 on 2018-11-01 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20181031_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes_dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 17, 10, 8, 655872)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 17, 10, 8, 655872)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.FileField(upload_to='user_profilepics'),
        ),
        migrations.AddField(
            model_name='likes_dislikes',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.blogdata'),
        ),
        migrations.AddField(
            model_name='likes_dislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
