# Generated by Django 2.0.6 on 2018-11-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20181101_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes_dislikes',
            old_name='choice',
            new_name='like_status',
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 17, 16, 14, 558314)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 17, 16, 14, 573939)),
        ),
    ]
