# Generated by Django 2.0.6 on 2018-11-01 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0004_auto_20181101_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 18, 54, 15, 65497)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 18, 54, 15, 65497)),
        ),
    ]
